name: Reusable worfklow with Semgrep

on:
  workflow_call:
    secrets:
      SEMGREP_APP_TOKEN:
        required: false
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main
      - master
    paths:
      - .github/workflows/semgrep.yml
  schedule:
    # random HH:MM to avoid a load spike on GitHub Actions at 00:00
    - cron: '44 8 * * *'
jobs:
  pass-secret-to-action:
    runs-on: ubuntu-latest
    steps:
      - name: Pass the received secret to an action
        uses: ./.github/actions/checkout@v4
        with:
          token: ${{ secrets.SEMGREP_APP_TOKEN }}

  pass-secret-to-workflow:
      uses: ./.github/workflows/semgrep.yml
      secrets:
       token: ${{ secrets.SEMGREP_APP_TOKEN}}
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
      SEMGREP_URL: https://cloudflare.semgrep.dev
      SEMGREP_APP_URL: https://cloudflare.semgrep.dev
      SEMGREP_VERSION_CHECK_URL: https://cloudflare.semgrep.dev/api/check-version
    container:
      image: returntocorp/semgrep:latest
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v4
      - run: semgrep ci
