name: Reusable workflow with Semgrep

on:
 workflow_call:
   
jobs:
  semgrep:
    name: Semgrep Scan
    runs-on: ubuntu-latest

    container:
      image: returntocorp/semgrep:latest
      
    if: (github.actor != 'dependabot[bot]')

    steps:
      - uses: actions/checkout@v4
      - run: semgrep ci
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

    
